# Multinomial Regression

## Preprocessing Data

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.utils import shuffle


df = pd.read_csv('50_Startups.csv')
print("data=\n",df)

df = shuffle(df).reset_index(drop=True)
print("Shuffled data =\n",df)


X = df.iloc[:,:-1].values # make X data into matrix/array
print("X=\n",X)

y = df.iloc[:,-1].values # make y data into matrix/array
print("y=\n",y)

#Categorical

#changing categories(text) into numbers for computation
from sklearn.preprocessing import LabelEncoder
le_X = LabelEncoder()
#change countries names to numbers
X[:,3] = le_X.fit_transform(X[:,3])
print("Categorized X = \n", X)


#to avoid the model to assume ranking countries as they aare categorized with numbers
from sklearn.preprocessing import OneHotEncoder  
encoder = OneHotEncoder(categorical_features=[3])
X = encoder.fit_transform(X).toarray()
print("Encoded X = \n", X)


from sklearn.cross_validation import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=0.2, random_state=0)
print("X Training = \n",X_train)
print("X Test = \n",X_test)
print("y Training = \n",y_train)
print("y Test = \n",y_test)




/home/shangeth/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/home/shangeth/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)


data=
     R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42     Florida  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87        127716.82  California  156122.51
7   130298.13       145530.06        323876.68     Florida  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08       110594.11        229160.95     Florida  146121.95
11  100671.96        91790.61        249744.55  California  144259.40
12   93863.75       127320.38        249839.44     Florida  141585.52
13   91992.39

Categorized X = 
 [[144372.41 118671.85 383199.62 2]
 [27892.92 84710.77 164470.71 1]
 [23640.93 96189.63 148001.11 0]
 [72107.6 127864.55 353183.81 2]
 [61136.38 152701.92 88218.23 2]
 [66051.52 182645.56 118148.2 1]
 [28663.76 127056.21 201126.82 1]
 [64664.71 139553.16 137962.62 0]
 [153441.51 101145.55 407934.54 1]
 [142107.34 91391.77 366168.42 1]
 [93863.75 127320.38 249839.44 1]
 [120542.52 148718.95 311613.29 2]
 [46014.02 85047.44 205517.64 2]
 [61994.48 115641.28 91131.24 1]
 [76253.86 113867.3 298664.47 0]
 [134615.46 147198.87 127716.82 0]
 [28754.33 118546.05 172795.67 0]
 [65605.48 153032.06 107138.38 2]
 [22177.74 154806.14 28334.72 0]
 [1000.23 124153.04 1903.93 2]
 [55493.95 103057.49 214634.81 1]
 [46426.07 157693.92 210797.67 0]
 [78013.11 121597.55 264346.06 0]
 [0.0 135426.92 0.0 0]
 [123334.88 108679.17 304981.62 0]
 [15505.73 127382.3 35534.17 2]
 [67532.53 105751.03 304768.73 1]
 [63408.86 129219.61 46085.25 0]
 [91992.39 135495.07 252664.93 0]
 [86419.7 153514.

/home/shangeth/.local/lib/python3.6/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


## Sklearn Model

In [2]:
from sklearn.linear_model import LinearRegression

reg = LinearRegression()
reg.fit(X_train,y_train)

y_pred = reg.predict(X_test)
print(y_pred)

[126133.08257807 151897.65285909 129010.23952768 159838.52428114
  69326.4212701   97837.3923064  114541.87122866 130390.43447333
 115529.84676529  98105.99981568]


In [3]:
from sklearn.metrics import r2_score
r2 = r2_score(y_test,y_pred)
print('r squared of the model = ',r2)

r squared of the model =  0.9352961588799316


## Backward Elimination

In [4]:
import statsmodels.formula.api as sm
X = np.append(arr=np.ones((50,1)).astype(int), values=X, axis=1)

In [5]:
X_opt = X[:,[0,1,2,3,4,5]]
reg_optimal = sm.OLS(endog=y, exog=X_opt).fit()
reg_optimal.summary()

#lower th ep value the more significant the dependent variable on independant variable


<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.948
Model:                            OLS   Adj. R-squared:                  0.943
Method:                 Least Squares   F-statistic:                     205.0
Date:                Mon, 06 Aug 2018   Prob (F-statistic):           2.90e-28
Time:                        01:02:12   Log-Likelihood:                -526.75
No. Observations:                  50   AIC:                             1064.
Df Residuals:                      45   BIC:                             1073.
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       4.122e+04   4607.941      8.945      0.000    3.19e+04    5.05e+04
x1          1.339e+04   2421.500      5.529      0.000    8511.111    1.83e+04
x2          1.448e+04   2518.987      5.748      0.000    9405.870    1.96e+04
x3          1.335e+04   2459.306      5.428      0.000    8395.623    1.83e+04
x4             0.8609      0.031     27.665      0.000       0.798       0.924
x5            -0.0527      0.050     -1.045      0.301      -0.154       0.049
==============================================================================
Omnibus:                       14.275   Durbin-Watson:                   1.578
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               19.260
Skew:                          -0.953   Prob(JB):                     6.57e-05
Kurtosis:                       5.369   Cond. No.                     1.61e+18
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 4.17e-25. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [12]:
# the p value of x5 id 30% , so we remove it as it does not have any imapact on y.
X_opt = X[:,[0,1,2,3,4]]
reg_optimal = sm.OLS(endog=y, exog=X_opt).fit()
reg_optimal.summary()


<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.947
Model:                            OLS   Adj. R-squared:                  0.943
Method:                 Least Squares   F-statistic:                     272.4
Date:                Sat, 04 Aug 2018   Prob (F-statistic):           2.76e-29
Time:                        09:21:38   Log-Likelihood:                -527.35
No. Observations:                  50   AIC:                             1063.
Df Residuals:                      46   BIC:                             1070.
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       3.686e+04   1959.786     18.806      0.000    3.29e+04    4.08e+04
x1          1.189e+04   1956.677      6.079      0.000    7955.697    1.58e+04
x2          1.306e+04   2122.665      6.152      0.000    8785.448    1.73e+04
x3           1.19e+04   2036.022      5.847      0.000    7805.580     1.6e+04
x4             0.8530      0.030     28.226      0.000       0.792       0.914
==============================================================================
Omnibus:                       13.418   Durbin-Watson:                   1.732
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               17.605
Skew:                          -0.907   Prob(JB):                     0.000150
Kurtosis:                       5.271   Cond. No.                     2.43e+17
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 6.33e-24. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""